name: Deploy Backend
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sundoladocker/realresumebackend:latest

  deploying:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: pull image
        run: docker pull sundoladocker/realresumebackend:latest
      - name: run docker container
        run: docker run -d -p 8080:8080 --name bun-backend-container -e MONGODB=${{ secrets.MONGODB }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -e AWS_REGION=${{ secrets.AWS_REGION }} -e AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} -e AWS_S3_BUCKET_URL=${{ secrets.AWS_S3_BUCKET_URL }} sundoladocker/realresumebackend